### ISSUE TITLE
Why you fuse the proprioception observation and image feats twice in the actor?

### ISSUE THREAD

**Issue by ergo-zyh** [hengyuan-hu/ibrl#1]
Like https://github.com/hengyuan-hu/ibrl/blob/492ba2d5f40943963ee99d884f3595b6d0cc80f1/rl/actor.py#L115 
to
https://github.com/hengyuan-hu/ibrl/blob/492ba2d5f40943963ee99d884f3595b6d0cc80f1/rl/actor.py#L124

This network design doesn't appear in the paper, can you explain why you design it?

**Comment by hengyuan-hu** [comment]
By default we don't use the `SpatialEmb` class in the actor. 

The second append is the common way of appending the prop. I was experimenting with the SpatialEmb stuff in the first version. I guess it does not hurt to have them at multiple places so I did not remove the one that has been working well.

**Comment by ergo-zyh** [comment]
Thanks a lot. And I wonder if the proposed algorithm is suitable especially for sparse reward setting, do you try the dense reward setting?

**Comment by hengyuan-hu** [comment]
I have not tried dense reward setting because that is unrealistic for real world tasks. If you have dense reward, algorithm does not matter that much.
