### ISSUE TITLE
Do you try the SAC as the RL backbone in your pipeline?

### ISSUE THREAD

**Issue by ergo-zyh** [hengyuan-hu/ibrl#2]
When I try to reproduce your proposed approach and use SAC as my RL backbone, I found that the actor distribution always appears NAN after the first update of the networks. I guess it's because that the log probability of the selected action in the action distribution is abnormal, do you have some similar experience? If you know how to solve the problem, I'd appreciate it if you'd tell me.

**Comment by hengyuan-hu** [comment]
I have not used SAC.
