### ISSUE TITLE
IBRL-RPL

### ISSUE THREAD

**Issue by lakshitadodeja** [hengyuan-hu/ibrl#4]
Hi, 

I had a question for the IBRL-RPL baseline. When we are querying the target q network for the RPL policy, should we pass only the residual action or  residual action + base action ? 
The original formulation of RPL learns the critic only for the residual action so I am not sure if IBRL-RPL are also doing the same thing

Also, do you use some burnin period for RPL where only the critic learns for the first few iterations ?

**Comment by hengyuan-hu** [comment]
I think either way should be fine, it probably won't make a huge difference. Just make sure the input to the critic is consistent for BC and RL actions. I used base+residual.

For critic burnin, I have not tried it with RPL but I tried it in the vanilla RL/RLPD/IBRL setting, it does not help in a meaningful way.

**Comment by lakshitadodeja** [comment]
Thank you for the reply ! I will try it out
